# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerUserName: 'ux007893'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build_Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        containerRegistry: 'DockerRegistry'
        command: 'login'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerRegistry'
        repository: 'ux007893/appliation'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
#          ux007893/appliation:latest
    - task: Docker@2
      displayName: Pushing Image to Docker Hub
      inputs:
        containerRegistry: 'DockerRegistry'
        repository: 'ux007893/appliation'
        command: 'push'
        tags: |
         $(tag)
#         latest
