apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  type: NodePort
  ports:
  - name: "test-service"
    port: 8080
    targetPort: 80
    nodePort: 5000
  selector:
    app: my-app