apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  type: NodePort
  ports:
  - name: "test-service"
    port: 80
    targetPort: 5000
    nodePort: 30080
  selector:
    app: myapp