name: Build and deploy Python app to EC2 virtual machine

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkou repositry
      uses: actions/checkout@v5
    - name: Set-UP Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: "pip"
    - name: Install all the dependencies 
      run: |
        python -m pip install --upgrade pip wheel
        pip install pytest
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest -q tests/test_app.py || echo "No tests found, skipping."
    